server:
  port: 8080
logging:
  level:
    cn.javastack.springboot.ai: DEBUG
spring:
  ai:
    ollama:
      base-url: http://192.168.0.109:11434
      chat:
        options:
             model: deepseek-r1:1.5b
             temperature: 0.7